### PR TITLE
2019-06-13 meeting minutes

### PR DESCRIPTION
**Pull request by piogor**
Hi, I am sending minutes from the meeting today.

### CODE REVIEW

**Comment by hardion** [comment]
Would not it be better to use the wiki for the minutes?

**Comment by piogor** [comment]
This may be reasonable. However, I do not have a strong opinion on it, as both approaches may serve their purpose :-) .
Having a meeting minutes along with sources may help in referencing. On the other side, it will create a PRs not directrly related to `valuable specification update`. I suggest to leave it as it is now and put it as a point to decide on the next meeting.

**Comment by piogor** [comment]
Anyway, I would then need access to the wiki.

**Comment by hardion** [comment]
You should have access to the wiki now.

**Comment by hardion** [comment]
My preference would go for the wiki to not pollute the specification source.

**Comment by piogor** [comment]
Ok, I have added the minutes as a wiki. One drawback is that GitHub wiki does not support hierarchical (tree, subpages) structure.

**Comment by hardion** [comment]
Yes sure. In wiki style we can make pointers from the first page.
I will close the MR if you are agree.

**Comment by piogor** [comment]
Yes, please close :)

Pobierz aplikację Outlook dla systemu Android<https://aka.ms/ghei36>

________________________________

**Comment by hardion** [comment]
I have made a landing page for the wiki with a link to your minutes.
Thanks for your contribution!

**Pull request closed without merging**
